version: "3"

networks:
  traefik-proxy:
    external: true

services:
  server:
    image: gitea/gitea:1.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - traefik-proxy
    volumes:
      - ./conf:/data/gitea/conf
      - /var/containers/gitea:/data
    ports:
      - "2222:22"
    labels:
      - "traefik.backend=gitea"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.frontend.rule=PathPrefixStrip:/git"
